source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Permissionable_Example', :exclusive => true do
  pod "Permissionable", :path => "../"
end

target 'Permissionable_Tests', :exclusive => true do
  pod "Permissionable", :path => "../"

  
end
